Pathways.components.get('letter-gallery').addData('marie-stopes-letters', {
    location: '_assets/galleries/marie-stopes-letters/',
    images: [{
        image: '01-HorridVice-pp-08-HIGHLIGHT',
        textSrc: '/_assets/text/marie-stopes-letters/01-letter.html',
        audio: 'http://s3-eu-west-1.amazonaws.com/digitalstories/digital-stories/the-collectors/audio-stopes-letters/01-HorridVice-Extract.mp3',
    }, {
        image: '02-HugeAppendage-Transcript-pp-03-HIGHLIGHT',
        textSrc: '/_assets/text/marie-stopes-letters/02-letter.html',
        audio: 'http://s3-eu-west-1.amazonaws.com/digitalstories/digital-stories/the-collectors/audio-stopes-letters/02-HugeAppendage-Extract.mp3',
    }, {
        image: '03-PositionsDuringPregnancy-pp-01-HIGHLIGHT',
        textSrc: '/_assets/text/marie-stopes-letters/03-letter.html',
        audio: 'http://s3-eu-west-1.amazonaws.com/digitalstories/digital-stories/the-collectors/audio-stopes-letters/03-PositionsDuringPregnancy-Extract.mp3',
    }, {
        image: '04-PleasureWithoutPregnancy-pp-0102-HIGHLIGHT',
        textSrc: '/_assets/text/marie-stopes-letters/04-letter.html',
        audio: 'http://s3-eu-west-1.amazonaws.com/digitalstories/digital-stories/the-collectors/audio-stopes-letters/04-PleasureWithoutPregnancy-Extract.mp3',
    }, {
        image: '05-LargeSexOrgans-pp-01-HIGHLIGHT',
        textSrc: '/_assets/text/marie-stopes-letters/05-letter.html',
        audio: 'http://s3-eu-west-1.amazonaws.com/digitalstories/digital-stories/the-collectors/audio-stopes-letters/05-LargeSexOrgans-Extract.mp3',
    }, {
        image: '06-GoBackHome-pp-01-HIGHLIGHT',
        textSrc: '/_assets/text/marie-stopes-letters/06-letter.html',
        audio: 'http://s3-eu-west-1.amazonaws.com/digitalstories/digital-stories/the-collectors/audio-stopes-letters/06-GoBackHome-Extract.mp3',
    }, {
        image: '07-FreeingTheCaptives-pp-01-HIGHLIGHT',
        textSrc: '/_assets/text/marie-stopes-letters/07-letter.html',
        audio: 'http://s3-eu-west-1.amazonaws.com/digitalstories/digital-stories/the-collectors/audio-stopes-letters/07-FreeingTheCaptives.mp3',
    }]
});
