#

site:
    pathways:
        mindcraft:
            path: '/pathways/1-mindcraft/'
            survey-link: 'http://survey.euro.confirmit.com/wix/p1839093604.aspx'
            modules:
                -   id: intro
                    path: 'index.php'
                    title: 'Mindcraft: A century of madness, murder and mental healing'
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'Mindcraft: A century of madness, murder and mental healing.'

                -   id: credits
                    path: 'credits.php'
                    title: 'Credits'
                    title_postfix: ' | Mindcraft | Wellcome Collection'
                    description: 'Production credits for Mindcraft, a digital story from Wellcome Collection.'

                -   id: mesmer
                    path: '1-mesmer/'
                    title: A new force in nature
                    title_postfix: ' | Mindcraft | Wellcome Collection'
                    description: 'Franz Anton Mesmer arrives in Paris to present a revolutionary theory to the French Academy of Sciences. He claims he has harnessed a universal life-force called ‘animal magnetism’ that can cure all disease.'
                    panels:
                        - id: mesmers-salon-intro
                        - id: mesmers-salon
                        - id: animal-magnetism
                        - id: satirised
                        - id: committee-investigates-intro
                        - id: committee-investigates

                -   id: airloom
                    path: '2-airloom/'
                    title: A machine to control the mind
                    title_postfix: ' | Mindcraft | Wellcome Collection'
                    description: 'A Welsh tea merchant, James Tilly Matthews, reveals that his mind is being controlled by a gang of “magnetic spies” and their secret machine, the Air Loom.'
                    panels:
                        - id: airloom-intro
                        - id: airloom
                        - id: where-will-this-technology-lead
                        - id: grisly-experiments

                -   id: elliotson
                    path: '3-elliotson/'
                    title: Who controls who?
                    title_postfix: ' | Mindcraft | Wellcome Collection'
                    description: 'Mesmerism is still being spread by a network of believers. Its most prominent champion in Britain is Dr John Elliotson, professor at University College Hospital.'
                    panels:
                        - id: okey-sisters
                        - id: thomas-wakley
                        - id: verdict

                -   id: esdaile
                    path: '4-esdaile/'
                    title: Mind over matter
                    title_postfix: ' | Mindcraft | Wellcome Collection'
                    description: 'The Zoist receives news that a British surgeon in India, James Esdaile, has performed dozens of pain-free operations by mesmerising his patients.'
                    panels:
                        - id: gonad-man
                        - id: fakir
                        - id: india
                        - id: surgery-under-hypnosis-intro
                        - id: surgery-under-hypnosis
                        - id: james-braid
                        - id: self-hypnosis

                -   id: svengali
                    path: '5-svengali/'
                    title: Dark forces
                    title_postfix: ' | Mindcraft | Wellcome Collection'
                    description: 'Hypnotism has now been accepted by medical science. ‘Mind over matter’ is real – but what are its limits and its dangers? Can it be exploited for evil ends?'
                    panels:
                        - id: trilby
                        - id: bompard

                -   id: freud
                    path: '6-freud/'
                    title: Secrets of the mind revealed
                    title_postfix: ' | Mindcraft | Wellcome Collection'
                    description: 'Hypnosis, tarnished by scandal and abuse, has fallen from medical favour. But two doctors still believe it holds the key to understanding the mind and its powers to heal.'
                    panels:
                        - id: anna-o
                        - id: fred-breuer-intro
                        - id: anna-o-video
                        - id: fred-breuer
                        - id: office
                        - id: office-2

        the-collectors:
            path: '/pathways/2-the-collectors/'
            # survey-link: 'http://www.google.com'
            modules:
                -   id: intro
                    path: 'index.php'
                    title: 'The Collectors: Searchers, secrets and the power of curiosity'
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'The Collectors'

                -   id: credits
                    path: 'credits.php'
                    title: 'Credits'
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'Production credits for The Collectors, a digital story from Wellcome Collection.'

                -   id: curious-gardener
                    path: '1-curious-gardener/'
                    title: The Curious Gardener
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'In 1634, anyone who spent a day at John Tradescant’s house and garden in south Lambeth could discover more curiosities than a man might see in a lifetime of travel.'
                    panels:
                        - id: john-tradescent
                        - id: duke-of-buckingham
                        - id: unique-artifacts
                        - id: tradescants-ark

                -   id: merchants-of-light
                    path: '2-merchants-of-light/'
                    title: Merchants of Light
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'While John Tradescant had been securing the most alluring and intriguing treasures from cooperative ships in the British fleet, lawyer and philosopher Francis Bacon developed a vision of a world where evidence and knowledge were collected through more ordered voyages of exploration.'
                    panels:
                        - id: bensalem-intro
                        - id: bensalem
                        - id: bensalem-outro

                -   id: death-collector
                    path: '3-death-collector/'
                    title: The Death Collector
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'At a time when plague periodically decimated London’s population, haberdasher John Graunt applied his knowledge of book-keeping to collect, analyse and interpret data relating to the City’s deaths.'
                    panels:
                        - id: bills-of-mortality
                        - id: gaunt-records
                        - id: death-infographic
                        - id: isaac-newton

                -   id: unceasing-seeker
                    path: '4-unceasing-seeker/'
                    title: The Unceasing Seeker
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'Like John Tradescant and John Graunt before him, Henry Solomon Wellcome came from humble beginnings and began collecting to support his business. By the end of his life, his collection was thought to consist of five times as many items as the Louvre.'
                    panels:
                        - id: wellcome-collection

                -   id: obscene-doctor
                    path: '5-obscene-doctor/'
                    title: The ‘Obscene’ Doctor
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'Whether paying a shilling to peek at an Italian anatomical model in a grocer’s shop on the Strand, or visiting a public museum, Londoners were avid consumers of anatomy collections in the eighteenth and early nineteenth century. '
                    panels:
                        - id: khans-anatomical-museum
                        - id: quackery
                        - id: obscene-publications-act
                        - id: joseph-khan
                        - id: seized-and-destroyed

                -   id: ignorant-bride
                    path: '6-ignorant-bride/'
                    title: The Ignorant Bride
                    title_postfix: ' | The Collectors | Wellcome Collection'
                    description: 'Brilliant young paleobotanist Marie Stopes was so ignorant about the workings of the human body that she claimed not to realise her own marriage was unconsummated.'
                    panels:
                        - id: british-museum
                        - id: married-love
                        - id: shared-experiences
                        - id: letters

        breath:
            path: '/pathways/3-breath/'

